/* Generated By:JavaCC: Do not edit this line. ChartExpressionCheckerConstants.java */
package sim.app.episim.charts.parser;

public @SuppressWarnings("all") interface ChartExpressionCheckerConstants {

  int EOF = 0;
  int PLUS = 5;
  int MINUS = 6;
  int TIMES = 7;
  int DIVIDE = 8;
  int OPEN_PAR = 9;
  int CLOSE_PAR = 10;
  int CLOSE_PA = 11;
  int IDENTIFIER = 12;
  int LETTER = 13;
  int DIGIT = 14;
  int NUMBER = 15;
  int DIGITS = 16;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<NUMBER>",
    "<DIGITS>",
    "\"Pow(\"",
    "\"Sqrt(\"",
  };

}
