/* Generated By:JavaCC: Do not edit this line. ChartExpressionCheckerConstants.java */
package sim.app.episim.charts.parser;

public @SuppressWarnings("all") interface ChartExpressionCheckerConstants {

  int EOF = 0;
  int ADD_SUBT_OP = 5;
  int MULT_DIV_OP = 6;
  int OPEN_PAR = 7;
  int CLOSE_PAR = 8;
  int REL_OP = 9;
  int BIG_SMALL = 10;
  int EQUAL = 11;
  int NOT = 12;
  int IDENTIFIER = 13;
  int LETTER = 14;
  int DIGIT = 15;
  int NUMBER = 16;
  int DIGITS = 17;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<ADD_SUBT_OP>",
    "<MULT_DIV_OP>",
    "\"(\"",
    "\")\"",
    "<REL_OP>",
    "<BIG_SMALL>",
    "<EQUAL>",
    "<NOT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<NUMBER>",
    "<DIGITS>",
    "\"Pow(\"",
    "\",\"",
    "\"ACMV(\"",
    "\"Sqrt(\"",
    "\"ACW(\"",
    "\"||\"",
    "\"&&\"",
  };

}
