/* Generated By:JavaCC: Do not edit this line. DataMonitoringExpressionCheckerConstants.java */
package sim.app.episim.datamonitoring.parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DataMonitoringExpressionCheckerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ADD_SUBT_OP = 5;
  /** RegularExpression Id. */
  int MULT_DIV_OP = 6;
  /** RegularExpression Id. */
  int OPEN_PAR = 7;
  /** RegularExpression Id. */
  int CLOSE_PAR = 8;
  /** RegularExpression Id. */
  int REL_OP = 9;
  /** RegularExpression Id. */
  int BIG_SMALL = 10;
  /** RegularExpression Id. */
  int EQUAL = 11;
  /** RegularExpression Id. */
  int NOT = 12;
  /** RegularExpression Id. */
  int IDENTIFIER = 13;
  /** RegularExpression Id. */
  int LETTER = 14;
  /** RegularExpression Id. */
  int SIGN = 15;
  /** RegularExpression Id. */
  int DIGIT = 16;
  /** RegularExpression Id. */
  int NUMBER = 17;
  /** RegularExpression Id. */
  int DIGITS = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<ADD_SUBT_OP>",
    "<MULT_DIV_OP>",
    "\"(\"",
    "\")\"",
    "<REL_OP>",
    "<BIG_SMALL>",
    "<EQUAL>",
    "<NOT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<SIGN>",
    "<DIGIT>",
    "<NUMBER>",
    "<DIGITS>",
    "\"Pow(\"",
    "\",\"",
    "\"ACMV(\"",
    "\"GRAD(\"",
    "\"CELL(\"",
    "\"Sqrt(\"",
    "\"ACW(\"",
    "\"||\"",
    "\"&&\"",
  };

}
